apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 507126860363.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 507126860363.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 403630a1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
